/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    MButton: typeof import('./../libs/m-button/index.vue')['default']
    MInfinite: typeof import('./../libs/m-infinite/index.vue')['default']
    MInfinity: typeof import('./../libs/m-infinity/index.vue')['default']
    MPopover: typeof import('./../libs/m-popover/index.vue')['default']
    MPopup: typeof import('./../libs/m-popup/index.vue')['default']
    MSearch: typeof import('./../libs/m-search/index.vue')['default']
    MSvgIcon: typeof import('./../libs/m-svg-icon/index.vue')['default']
    MWaterfall: typeof import('./../libs/m-waterfall/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
